name: Deploy Astro

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: webhost
        run: npm install

      - name: Build Astro
        working-directory: webhost
        run: npm run build

      - name: Disable Jekyll
        run: echo "" > webhost/dist/.nojekyll

      - name: List dist content
        run: ls -R webhost/dist


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: webhost/dist
