name: Deploy Astro

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show repo tree
        run: ls -R

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Webhost
          npm install

      - name: Build Astro
        run: |
          cd Webhost
          npm run build

      - name: Verify dist
        run: ls -R Webhost/dist

      - name: Disable Jekyll
        run: echo "" > Webhost/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Webhost/dist
